apiVersion: v1
kind: ServiceAccount
metadata:
  name: insecure-app-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insecure-app-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insecure-app-binding
subjects:
- kind: ServiceAccount
  name: insecure-app-sa
  namespace: dev
roleRef:
  kind: ClusterRole
  name: insecure-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: insecure-app
  labels:
    app: insecure-app
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: insecure-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  labels:
    app: insecure-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      serviceAccountName: insecure-app-sa
      containers:
      - name: insecure-app
        image: lastcoolnameleft/insecure-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password