apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-sa-namespace-admin
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:dev:default
---
apiVersion: v1
kind: Service
metadata:
  name: insecure-app
  labels:
    app: insecure-app
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: insecure-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  labels:
    app: insecure-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      serviceAccountName: default
      containers:
      - name: insecure-app
        image: lastcoolnameleft/insecure-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password